name: Issue Management Automation

on:
  issues:
    types: [labeled] # We only care about when issues are labeled

jobs:
  # Job 1: Auto-close issues labeled "duplicate"
  auto-close-duplicate:
    runs-on: ubuntu-latest
    name: Auto-close Duplicate Issues
    # Run only when an issue is labeled 'duplicate'
    if: github.event.label.name == 'duplicate'
    steps:
      - name: Close issue as duplicate
        uses: peter-evans/close-issue@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          comment: "This issue has been marked as a duplicate and is now being automatically closed."
          close-reason: "completed"
          
  # Job 2: Auto-add issues labeled "roadmap" to project
  add-to-project:
    runs-on: ubuntu-latest
    name: Add 'roadmap' issues to Project
    # Run only when an issue is labeled 'roadmap'
    if: github.event.label.name == 'roadmap'
    steps:
      - name: Add issue to project
        uses: actions/add-to-project@v0.5.0
        with:
          project-url: "https://github.com/orgs/Launchpad-Incubator/projects/6"
          github-token: ${{ secrets.GITHUB_TOKEN }}

  # Job 3: Auto-close issues labeled "status done"
  auto-close-done:
    runs-on: ubuntu-latest
    name: Auto-close Done Issues
    # Run only when an issue is labeled 'status done'
    if: github.event.label.name == 'status done'
    steps:
      - name: Close issue as completed
        uses: peter-evans/close-issue@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          comment: "This issue has been marked with 'status done' and is now being automatically closed as completed."
          close-reason: "completed"
